# generated by terranix-openstack : openstack.export.nix
# it lists every return value created
# by the openstack provider in nix format
# so you can import it in another nix-lang tool
{


# openstack servers:
axel = {
  host = {
    ipv4 = "192.168.2.20";
    ipv6 = "";
    ipv4-floating = "192.168.2.20";
  };
  location = "garr-pa1";
};

kelpie = {
  host = {
    ipv4 = "192.168.1.200";
    ipv6 = "";
    ipv4-floating = "192.168.1.200";
  };
  location = "garr-pa1";
};

}
